backend:
    name: git-gateway # Prod
    repo: recrea-t/aneu-coworking
    branch: main


media_folder: static/images
public_folder: /images

site_url: https://aneu-coworking.netlify.app
display_url: https://aneu-coworking.netlify.app
logo_url: https://aneu-coworking.netlify.app/images/Logo.svg
locale: "ca"

collections:
    #Sections (Catalan)
    - name: 'sections-ca' # Used in routes, e.g., /admin/collections/blog
      label: 'Seccions (Català)' # Used in the UI
      folder: 'src/pages/sections' # The path to the folder where the documents are stored
      create: false # Allow users to create new documents in this collection
      slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      extension: 'ca.md'
      format: frontmatter
      fields: # The fields for each document, usually in front matter
          - { label: 'Títol', name: 'title', widget: 'string' }

    #Sections (Spanish)
    - name: 'sections-es' # Used in routes, e.g., /admin/collections/blog
      label: 'Secciones (Español)' # Used in the UI
      folder: 'src/pages/sections' # The path to the folder where the documents are stored
      create: false # Allow users to create new documents in this collection
      slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      extension: 'es.md'
      format: frontmatter
      fields: # The fields for each document, usually in front matter
          - { label: 'Título', name: 'title', widget: 'string' }

    #Sections (English)
    - name: 'sections-en' # Used in routes, e.g., /admin/collections/blog
      label: 'Sections (English)' # Used in the UI
      folder: 'src/pages/sections' # The path to the folder where the documents are stored
      create: false # Allow users to create new documents in this collection
      slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      extension: 'en.md'
      format: frontmatter
      fields: # The fields for each document, usually in front matter
          - { label: 'Title', name: 'title', widget: 'string' }

    #Pages (Catalan)
    - name: 'pages-ca' # Used in routes, e.g., /admin/collections/blog
      label: 'SEO (Català)' # Used in the UI
      folder: 'src/pages' # The path to the folder where the documents are stored
      slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      extension: 'ca.md'
      format: frontmatter
      fields: # The fields for each document, usually in front matter
          - { label: 'Títol (SEO)', name: 'title', widget: 'string' }
          - { label: 'Descripció (SEO)', name: 'description', widget: 'text' }

    #Pages (Spanish)
    - name: 'pages-es' # Used in routes, e.g., /admin/collections/blog
      label: 'SEO (Español)' # Used in the UI
      folder: 'src/pages' # The path to the folder where the documents are stored
      slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      extension: 'es.md'
      format: frontmatter
      fields: # The fields for each document, usually in front matter
          - { label: 'Título (SEO)', name: 'title', widget: 'string' }
          - { label: 'Descripción (SEO)', name: 'description', widget: 'text' }

    #Pages (English)
    - name: 'pages-en' # Used in routes, e.g., /admin/collections/blog
      label: 'SEO (English)' # Used in the UI
      folder: 'src/pages' # The path to the folder where the documents are stored
      slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
      extension: 'en.md'
      format: frontmatter
      fields: # The fields for each document, usually in front matter
          - { label: 'Title (SEO)', name: 'title', widget: 'string' }
          - { label: 'Description (SEO)', name: 'description', widget: 'text' }
